# Generated by Django 3.0.5 on 2020-04-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0005_booksadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksAdmin',
        ),
    ]
