# Generated by Django 3.0.5 on 2020-04-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysearchface',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
