# Generated by Django 3.0.5 on 2020-04-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200406_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('passport', models.CharField(max_length=12, verbose_name='Паспорт')),
                ('surname', models.TextField(verbose_name='Характеристика')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=main.models.Suspect.get_image_name)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Подозреваймый',
                'verbose_name_plural': 'Подозреваймые',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
