# Generated by Django 3.0.5 on 2020-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200406_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='crimes',
            field=models.TextField(default=2, verbose_name='Характеристика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suspect',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
