# Generated by Django 3.0.5 on 2020-04-07 14:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200406_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.Suspect.get_image_name, verbose_name='Фотопортрет'),
        ),
    ]
