# Generated by Django 3.0.5 on 2020-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200407_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='<em>ДД.MM.ГГГГ</em>', null=True, verbose_name='Дата рождения'),
        ),
    ]
